# version: "3"
# services:
#   postgres:
#     image: "postgres:latest"
#     restart: "no"
#     environment:
#       - PGUSER=postgres
#       - PGPASSWORD=postgres_password
#       - POSTGRES_HOST_AUTH_METHOD=trust
#   redis:
#     image: "redis:latest"
#     restart: "no"
#   nginx:
#     restart: always
#     build:
#       context: ./nginx
#       dockerfile: Dockerfile.dev
#     ports:
#       - "4200:80"
#   api:
#     build:
#       context: ./server
#       dockerfile: Dockerfile.dev
#     volumes:
#       - /app/node_modules
#       - ./server:/app
#     environment:
#       - REDISHOST=redis
#       - REDISPORT=6379
#       - PGPORT=5432
#       - PGUSER=postgres
#       - PGDATABASE=postgres
#       - PGPASSWORD=postgres_password
#       - PGHOST=postgres
      
#   client:
#     build:
#       context: ./client
#       dockerfile: Dockerfile.dev
#     volumes:
#       - /app/node_modules
#       - ./client:/app
#   worker:
#     build:
#       context: ./worker
#       dockerfile: Dockerfile.dev
#     volumes:
#       - /app/node_modules
#       - ./worker:/app    
#     environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4200:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
